steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/$PROJECT_ID/survaq-jobs/$_BUILD_CONTEXT:$COMMIT_SHA
      - --destination=gcr.io/$PROJECT_ID/survaq-jobs/$_BUILD_CONTEXT:latest
      - --cache=true
      - --build-arg=BUILD_CONTEXT=$_BUILD_CONTEXT

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'beta'
      - 'run'
      - 'jobs'
      - 'update' # update or create
      - 'survaq-jobs-$_BUILD_CONTEXT-us-west1'
      - '--image=gcr.io/$PROJECT_ID/survaq-jobs/$_BUILD_CONTEXT:latest'
      - '--region'
      - 'us-west1'
      - '--max-retries'
      - '0'
      - '--set-env-vars'
      - '$_ENV_VARS'
      - '--service-account'
      - '$_SERVICE_ACCOUNT'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'scheduler'
      - 'jobs'
      - 'update' # update or create
      - 'http'
      - 'survaq-jobs-$_BUILD_CONTEXT-scheduler'
      - '--location'
      - 'us-west1'
      - '--schedule=$_SCHEDULE'
      - '--time-zone'
      - 'Asia/Tokyo'
      - '--uri=https://us-west1-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/$PROJECT_ID/jobs/survaq-jobs-$_BUILD_CONTEXT-us-west1:run'
      - '--http-method'
      - 'POST'
      - '--oauth-service-account-email'
      - '$PROJECT_NUMBER-compute@developer.gserviceaccount.com'

substitutions:
  _BUILD_CONTEXT: ''
  _ENV_VARS: ''
  _SERVICE_ACCOUNT: ''
  _SCHEDULE: '0 * * * *'