steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/$PROJECT_ID/survaq-jobs/$_BUILD_CONTEXT:$COMMIT_SHA
      - --destination=gcr.io/$PROJECT_ID/survaq-jobs/$_BUILD_CONTEXT:latest
      - --cache=true
      - --build-arg=BUILD_CONTEXT=$_BUILD_CONTEXT
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'beta'
      - 'run'
      - 'jobs'
      - 'update'
      - 'survaq-jobs-$_BUILD_CONTEXT'
      - '--region'
      - 'europe-west9'
      - '--set-env-vars'
      - '$_ENV_VARS'
      - '--service-account'
      - '$_SERVICE_ACCOUNT'

substitutions:
  _BUILD_CONTEXT: ''
  _ENV_VARS: ''
  _SERVICE_ACCOUNT: ''